apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  # Data to be replicated into OPA
  sync:
    syncOnly:
      - group: "apps"
        version: "v1"
        kind: "Deployment"
      - group: "extensions"
        version: "v1beta1"
        kind: "Deployment"
