---
apiVersion: v1
kind: Service
metadata:
  labels:
    gatekeeper.sh/system: "yes"
  name: gatekeeper-webhook-service
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    control-plane: controller-manager
    gatekeeper.sh/system: "yes"
