apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - security_controls_template.yml
  - unique_ingress_template.yml
  - livenessprobe_template.yml
  - readinessproble_template.yml
