- op: "add"
  path: "/spec/match"
  value:
    excludedNamespaces:
      - kube-system
      - logging
      - monitoring
      - ingress-nginx
    kinds:
      - apiGroups: ["apps", "extensions"]
        kinds: ["Deployment"]
