resources:
  - must_have_security_controls.yml
  - must_have_unique_ingresses.yml
  - must_have_unique_service_selector.yml

patchesJson6902:
  - target:
      group: constraints.gatekeeper.sh
      version: v1beta1
      kind: SecurityControls
      name: enforce-deployment-and-pod-security-controls
    path: patches/all-matches.yml
  - target:
      group: constraints.gatekeeper.sh
      version: v1beta1
      kind: K8sUniqueIngressHost
      name: unique-ingress-host
    path: patches/ingress-matches.yml
